version: "3"

services:
  tutorial1:
    build:
      context: ./tutorial-01
    ports:
      - "4201:4242"
    hostname: tutorial1
    
  tutorial2:
    build:
      context: ./tutorial-02
    ports:
      - "4202:4242"
    hostname: tutorial2
    
  tutorial3:
    build:
      context: ./tutorial-03
    ports:
      - "4203:4242"
    hostname: tutorial3
    
  tutorial4:
    build:
      context: ./tutorial-04
    ports:
      - "4204:4242"
    hostname: tutorial4
  
  tutorial5:
    build:
      context: ./tutorial-05
    ports:
      - "4205:4242"
    hostname: tutorial5
